### ISSUE TITLE
Call of String(double,uint8_t) is ambiguous

### ISSUE THREAD

**Issue by towler73** [PunchThrough/PunchThrough-BEAN-Arduino-Firmware#23]
I tried to compile a sketch using [ArduinoJson](https://github.com/bblanchon/ArduinoJson) Library and got a compile error.  I filed a issue [#142](https://github.com/bblanchon/ArduinoJson/issues/142) with ArduinoJson, and the response was that there is an issue with Bean String class.  See linked issue for complete response.  

Thanks,
Brett

**Comment by mplewis** [comment]
Hey @towler73, thanks for the detailed bug report and research. We'll look into getting this working with the Bean's version of the String class.

**Comment by towler73** [comment]
Great, thank you.  I looked into fixing myself, but C++ isn't my native language.

**Comment by bblanchon** [comment]
@towler73 You closed the issue but it's not fixed yet.

**Comment by towler73** [comment]
My mistake, I didn't mean to close.

**Comment by swstack** [comment]
Nice catch @bblanchon  :)

**Comment by mplewis** [comment]
@bblanchon closed [#142](https://github.com/bblanchon/ArduinoJson/issues/142) by removing the constructor in question, so it looks like this issue is no longer relevant. Is this correct @towler73?

**Comment by towler73** [comment]
That's correct, it's works now with the change that @bblanchon made.
